from __future__ import annotations

from datetime import date

import pandas as pd

from v182.decision import ipo_outcomes_v1_2 as outcomes


def _history_group() -> pd.DataFrame:
    frame = pd.DataFrame([
        {
            "identity_key": "TICKER:TEST",
            "observed_at_utc": "2026-01-08T20:00:00Z",
            "expected_date": "2026-01-10",
            "symbol": "TEST",
            "exchange": "NASDAQ",
            "decision": "WATCH",
            "net_ipo_score": "60",
            "price_mid": "10",
            "sec_ipo_price": "",
        },
        {
            "identity_key": "TICKER:TEST",
            "observed_at_utc": "2026-01-09T20:00:00Z",
            "expected_date": "2026-01-10",
            "symbol": "TEST",
            "exchange": "NASDAQ",
            "decision": "DEEP_DD",
            "net_ipo_score": "70",
            "price_mid": "11",
            "sec_ipo_price": "12",
        },
        {
            "identity_key": "TICKER:TEST",
            "observed_at_utc": "2026-01-10T08:00:00Z",
            "expected_date": "2026-01-10",
            "symbol": "TEST",
            "exchange": "NASDAQ",
            "decision": "PRIORITY_DD",
            "net_ipo_score": "90",
            "price_mid": "13",
            "sec_ipo_price": "14",
        },
    ])
    frame["_expected_date"] = frame["expected_date"].map(outcomes._as_date)
    frame["_observed_ts"] = frame["observed_at_utc"].map(outcomes._as_timestamp)
    return frame


def test_snapshot_is_strictly_before_actual_first_trade_date() -> None:
    snapshot = outcomes._strict_prelisting_snapshot(_history_group(), date(2026, 1, 10))
    assert snapshot is not None
    assert snapshot["decision"] == "DEEP_DD"
    assert snapshot["net_ipo_score"] == "70"
    assert snapshot["observed_at_utc"] == "2026-01-09T20:00:00Z"


def test_offer_price_prefers_prospectus_price_then_midpoint() -> None:
    price, source = outcomes._offer_price({"sec_ipo_price": "12", "price_mid": "10"})
    assert price == 12.0
    assert source == "SEC_PROSPECTUS_IPO_PRICE"
    price, source = outcomes._offer_price({"sec_ipo_price": "", "price_mid": "10"})
    assert price == 10.0
    assert source == "PRELISTING_PRICE_RANGE_MIDPOINT"


def test_price_metrics_include_offer_returns_drawdown_and_max_gain() -> None:
    index = pd.date_range("2026-01-10", periods=60, freq="B")
    close = [12.0, 10.0, 13.0, 14.0, 15.0] + [15.0] * 55
    prices = pd.DataFrame({"Close": close}, index=index)
    metrics = outcomes.price_metrics_v1_2(prices, 10.0)
    assert metrics["actual_first_trade_date"] == "2026-01-12"  # first business day generated by pandas
    assert metrics["ret_first_close_vs_offer_pct"] == 20.0
    assert metrics["ret_d5_from_offer_pct"] == 50.0
    assert metrics["max_drawdown_d5_from_first_close_pct"] == -16.67
    assert metrics["max_gain_d5_from_first_close_pct"] == 25.0
    assert metrics["max_drawdown_d5_from_offer_pct"] == 0.0
    assert metrics["max_gain_d5_from_offer_pct"] == 50.0
    assert metrics["ret_d20_from_offer_pct"] == 50.0
    assert metrics["ret_d60_from_offer_pct"] == 50.0


def test_validation_summary_never_promotes_and_can_measure_score_relation() -> None:
    frame = pd.DataFrame([
        {
            "decision_pre_listing": "DEEP_DD",
            "net_ipo_score_pre_listing": 65 + i,
            "ret_d20_from_offer_pct": -5 + i * 2,
            "ret_d60_from_offer_pct": -3 + i * 2,
        }
        for i in range(10)
    ])
    summary = outcomes.validation_summary_v1_2(frame, "2026-08-16T00:00:00Z")
    assert summary["validation_layer"] == "IPO_OUTCOMES_V1.2_PIT_SAFE"
    assert summary["d20_sample_count"] == 10
    assert summary["score_spearman_d20"] == 1.0
    assert summary["promotion_ready"] is False
    assert summary["calibration_status"] == "INSUFFICIENT_MATURED_SAMPLE"
    assert summary["pit_snapshot_policy"] == "STRICTLY_BEFORE_ACTUAL_FIRST_TRADING_DATE"
