from __future__ import annotations
from datetime import datetime, timezone
from pathlib import Path
import argparse
import json
import logging
import os

from v182.reporting import run as enrichment_run
from v182.reporting import etf_structure_refresh, etf_mt_v2081_run, committee_master_v21_4, committee_performance_v21_4
from v182.decision import gold_v1_1

logger=logging.getLogger(__name__)
ROOT=Path(__file__).resolve().parents[3]
SOFTWARE_VERSION="21.6.3"
PROCESS_VERSION="UNIFIED_V21_6_3_BOURSORAMA_DEEP_ATTRIBUTED"


def _safe_step(name:str,func)->dict:
    try:
        result=func(); result=dict(result.__dict__) if hasattr(result,"__dict__") else result
        return {"status":"SUCCESS","result":result}
    except Exception as exc:
        logger.exception("Unified runner step %s failed; independent steps continue",name)
        return {"status":"FAILED","error":type(exc).__name__,"detail":str(exc)[:500]}


def _skip_dependency(reason:str)->dict:
    return {"status":"SKIPPED_DEPENDENCY","reason":reason}


def _exit_code(payload:dict)->int:
    """Scheduled/CLI runs must fail visibly when the full process is not complete."""
    return 0 if payload.get("status")=="SUCCESS" else 1


def _boursorama_attributed_import(root:Path)->dict:
    """Ingest user/authorized Boursorama snapshots; never fetch Boursorama automatically."""
    from v182.io.frames import load_master, save_master, apply_observations
    from v182.reporting.collection_audit import write_collection_audit
    from v182.sources.boursorama_import import load_boursorama_imports, write_capture_worklist, write_import_audit
    from v182.sources.boursorama_current_summary import load_current_summaries
    from v182.sources.boursorama_bulk_import import load_bulk_consensus_pages
    from v182.sources.boursorama_action_extended import load_action_extended_pages
    from v182.sources.boursorama_company_calendar import load_company_calendar_pages
    from v182.sources.boursorama_etf_import import load_etf_pages

    actions_path=root/"outputs"/"V18.2_PEA_ACTIONS_MASTER_ENRICHED.csv"
    etfs_path=root/"outputs"/"V18.2_PEA_ETF_MASTER_ENRICHED.csv"
    if not actions_path.exists() or not etfs_path.exists():
        raise FileNotFoundError("Boursorama import requires current enriched Action and ETF masters")
    actions=load_master(actions_path); etfs=load_master(etfs_path)

    generic_obs,failures,stats=load_boursorama_imports(root,actions,etfs)
    # The general loader remains responsible for Action consensus pages and
    # attributed CSV/XLSX. Its HTML ETF observations are discarded here and
    # regenerated by the stricter ETF loader so a rendered '/7' can never be
    # misread as a risk score of 7/7.
    observations=[o for o in generic_obs if o.get("universe")!="ETF"]
    current_obs,current_fail,current_stats=load_current_summaries(root,actions)
    bulk_obs,bulk_fail,bulk_stats=load_bulk_consensus_pages(root,actions)
    extended_obs,extended_fail,extended_stats=load_action_extended_pages(root,actions)
    calendar_obs,calendar_fail,calendar_stats=load_company_calendar_pages(root,actions)
    etf_obs,etf_fail,etf_stats=load_etf_pages(root,etfs)
    observations.extend(current_obs)
    observations.extend(bulk_obs)
    observations.extend(extended_obs)
    observations.extend(calendar_obs)
    observations.extend(etf_obs)
    failures.extend(current_fail)
    failures.extend(bulk_fail)
    failures.extend(extended_fail)
    failures.extend(calendar_fail)
    failures.extend(etf_fail)
    stats["current_summary"]=current_stats
    stats["bulk_consensus"]=bulk_stats
    stats["action_extended"]=extended_stats
    stats["company_calendar"]=calendar_stats
    stats["safe_etf_pages"]=etf_stats

    action_obs=[o for o in observations if o.get("universe")=="ACTION"]
    etf_obs=[o for o in observations if o.get("universe")=="ETF"]
    actions,qa=apply_observations(actions,action_obs)
    etfs,qe=apply_observations(etfs,etf_obs)
    quarantined=qa+qe
    save_master(actions,actions_path); save_master(etfs,etfs_path)
    outdir=root/"outputs"/"data_audit"
    audit=write_import_audit(root,observations,failures+quarantined,stats,outdir)
    global_audit=write_collection_audit(
        actions,etfs,"WAVE_BOURSORAMA_DEEP_ATTRIBUTED",outdir,
        failures=failures+quarantined,
        source_context=(
            "Boursorama attributed HTML/CSV/XLSX after online refresh: FactSet consensus/PER/dividends, "
            "Cofisem company/key-figure context, company/dividend calendars, TEC technical context and Morningstar ETF "
            "characteristics/performance/composition. New complex fields remain context/shadow unless an existing "
            "canonical semantic match is explicit; ETF graphical risk remains missing without an explicit numerator."
        ),
    )
    worklist=write_capture_worklist(root,actions,etfs,root/"outputs"/"gaps"/"V21_BOURSORAMA_CAPTURE_WORKLIST.csv")
    return {
        **audit,
        "action_observations":len(action_obs),
        "etf_observations":len(etf_obs),
        "current_summary_observations":len(current_obs),
        "bulk_consensus_observations":len(bulk_obs),
        "bulk_consensus_matched_rows":int(bulk_stats.get("matched_rows",0)),
        "action_extended_observations":len(extended_obs),
        "action_extended_matched_rows":int(extended_stats.get("matched_rows",0)),
        "company_calendar_observations":len(calendar_obs),
        "company_calendar_matched_rows":int(calendar_stats.get("matched_rows",0)),
        "company_calendar_upcoming_events":int(calendar_stats.get("upcoming_events",0)),
        "etf_detail_files":int(etf_stats.get("detail_files",0)),
        "etf_explicit_risk_rows":int(etf_stats.get("explicit_risk_rows",0)),
        "merge_quarantined":len(quarantined),
        "capture_worklist":worklist,
        "collection_audit_after_boursorama":global_audit,
        "merge_policy":"Evidence/freshness aware; missing never overwrites observed data.",
        "automated_boursorama_retrieval":False,
        "new_complex_fields_score_weight_change":False,
    }


def run(root:Path=ROOT)->dict:
    """V21.6.3 runtime with deep attributed Boursorama intake and traceable model versions."""
    outdir=root/"outputs"/"unified"; outdir.mkdir(parents=True,exist_ok=True); run_id=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    steps={}
    steps["refresh"]=_safe_step("refresh",enrichment_run.run)
    if steps["refresh"]["status"]=="SUCCESS":
        steps["boursorama_attributed"]=_safe_step("boursorama_attributed",lambda:_boursorama_attributed_import(root))
    else:
        steps["boursorama_attributed"]=_skip_dependency("Requires SUCCESS current refresh before evidence-aware attributed merge.")
    steps["etf_structure"]=_safe_step("etf_structure",lambda:etf_structure_refresh.run(root))
    steps["etf_mt"]=_safe_step("etf_mt",etf_mt_v2081_run.run)
    steps["gold"]=_safe_step("gold",lambda:gold_v1_1.run(root,os.environ.get("FRED_API_KEY")))
    if steps["refresh"]["status"]=="SUCCESS" and steps["boursorama_attributed"]["status"]=="SUCCESS":
        steps["committee"]=_safe_step("committee",lambda:committee_master_v21_4.run(root))
    else:
        steps["committee"]=_skip_dependency("Requires SUCCESS current refresh and Boursorama attributed intake step; stale or unmerged Action masters are forbidden for Committee decisions.")
    if steps["refresh"]["status"]=="SUCCESS" and steps["committee"]["status"]=="SUCCESS":
        steps["performance"]=_safe_step("performance",lambda:committee_performance_v21_4.run(root))
    else:
        steps["performance"]=_skip_dependency("Requires SUCCESS refresh and SUCCESS current Committee; stale decisions are forbidden for virtual transactions.")
    outputs={
        "decisions":"outputs/committee_master/COMMITTEE_DECISIONS.csv","sector_ranking":"outputs/committee_master/SECTOR_RANKING.csv","sector_ranking_challenger":"outputs/committee_master/SECTOR_RANKING_CHALLENGER_V21_4.csv","action_reference_vs_challenger":"outputs/committee_master/ACTION_REFERENCE_VS_CHALLENGER_V21_4.csv","criteria_coverage":"outputs/committee_master/CRITERIA_COVERAGE.csv","effective_weights":"outputs/committee_master/EFFECTIVE_WEIGHTS_100.xlsx","tct_baseline":"outputs/committee_master/TCT_BASELINE_V24_1_8.csv","tct_shadow":"outputs/committee_master/TCT_SHADOW_V24_1_7.csv","collection_audit_latest":"outputs/data_audit/COLLECTION_DATA_AVAILABILITY_LATEST.xlsx","provenance":"state/provenance/OBSERVATION_PROVENANCE.csv","sector_rotation":"outputs/V21_3_SECTOR_ROTATION.csv","performance_workbook":"outputs/performance/COMMITTEE_BUY_PERFORMANCE.xlsx","etf_mt_ranking":"outputs/etf_mt_v2081/V20.8.1_ETF_MT_RANKING.csv","etf_mt_summary":"outputs/etf_mt_v2081/V20.8.1_ETF_MT_SUMMARY.json","gold_decision":"outputs/gold_v1_1/GOLD_V1_1_DECISION.json","gold_criteria":"outputs/gold_v1_1/GOLD_V1_1_CRITERIA.csv","gold_sources":"outputs/gold_v1_1/GOLD_V1_1_SOURCE_STATUS.csv","boursorama_import_summary":"outputs/data_audit/BOURSORAMA_IMPORT_SUMMARY.json","boursorama_import_observations":"outputs/data_audit/BOURSORAMA_IMPORT_OBSERVATIONS.csv","boursorama_capture_worklist":"outputs/gaps/V21_BOURSORAMA_CAPTURE_WORKLIST.csv"
    }
    existing={k:v for k,v in outputs.items() if (root/v).exists()}; failed=[k for k,v in steps.items() if v["status"]=="FAILED"]; skipped=[k for k,v in steps.items() if v["status"].startswith("SKIPPED")]; overall="SUCCESS" if not failed and not skipped else "PARTIAL_SUCCESS"
    decision_tracks={"actions_final":"V21.0 frozen-weight reference on current 1829 universe","actions_challenger":"V21.4 enriched shadow challenger","etf_mt_reference":"V20.8.1 exact 38-PIT core","etf_mt_challenger":"V20.8.2 missing-data dynamic shadow","tct":"V24.1.8 baseline + exact V24.1.7 T1/T2 shadow","gold":"V1.1 shadow"}
    payload={
        "version":PROCESS_VERSION,"software_version":SOFTWARE_VERSION,"run_id":run_id,"generated_at_utc":datetime.now(timezone.utc).isoformat(),"status":overall,"live_orders_enabled":False,"steps":steps,"persisted_outputs":existing,"decision_tracks":decision_tracks,
        "governance":[
            "Runtime/software version is distinct from model versions; decision_tracks is the authoritative model-version map.",
            "Boursorama is high-priority attributed input only: no automated Boursorama retrieval is performed because its published CGU prohibit automated recovery.",
            "Boursorama Action intake covers consensus, current estimates, company profile, multi-year key figures, PER/dividend/52-week palmares, company/dividend calendars and TEC technical context when saved pages are supplied.",
            "Only exact existing semantics populate canonical fields; newly exposed accounting, event, 52-week and TEC data remain context/shadow until dedicated PIT/OOS validation.",
            "Boursorama ETF intake covers Morningstar rating/category, explicit risk, characteristics, management-fee maximum, replication, net assets, performance/category comparison and composition when observed.",
            "A management-fee maximum is not relabelled as TER, and ETF risk_indicator is retained only when the 1..7 numerator is explicitly observable, never inferred from a rendered '/7'.",
            "The global collection-availability workbook is republished after Boursorama merge so Committee coverage and provenance reflect retained Boursorama values.",
            "Missing canonical Action ISINs are materialized as identity-only rows; no ticker/name/market data are invented.",
            "New/unvalidated Action factors, including 52-week overlays, remain challenger-only until dedicated PIT/OOS validation.",
            "Every collection publishes retained-value provenance plus missing/partial/available data.",
            "Per-field retained provenance governs evidence/freshness merge decisions and persists across runs.",
            "Dynamic available-criterion weights renormalize to 100% while minimum coverage gates remain active.",
            "Virtual BUYs execute no earlier than the next observed run and one consolidated position is allowed per ISIN.",
            "Virtual performance is model-version cohorted and never consumes stale Committee decisions.",
            "A partial unified run returns a non-zero CLI exit code so GitHub cannot display false green success.",
            "T1/T2 are ACTION TCT only.",
            "ETF MT 90.91% historical OOS attribution belongs only to exact V20.8.1 38-PIT core.",
            "No real orders are emitted."
        ]
    }
    path=outdir/f"UNIFIED_SUMMARY_{run_id}.json"; path.write_text(json.dumps(payload,ensure_ascii=False,indent=2,default=str),encoding="utf-8"); (outdir/"UNIFIED_SUMMARY_LATEST.json").write_text(json.dumps(payload,ensure_ascii=False,indent=2,default=str),encoding="utf-8"); print(json.dumps(payload,ensure_ascii=False,indent=2,default=str)); return payload


def main():
    parser=argparse.ArgumentParser(); parser.add_argument("--root",default=str(ROOT)); args=parser.parse_args(); payload=run(Path(args.root)); raise SystemExit(_exit_code(payload))


if __name__=="__main__": main()
